export enum Status{
    ABAIXO_DO_PESO = "ABAIXO DO PESO",
    PESO_NORMAL = "PESO NORMAL",
    SOBREPESO = "SOBREPESO",
    OBESIDADE_GRAU_1 = "OBESIDADE GRAU 1",
    OBESIDADE_GRAU_2 = "OBESIDADE GRAU 2",
    OBESIDADE_GRAU_3 = "OBESIDADE GRAU 3"
}